kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  client-header-timeout: "600"
  client-body-timeout: "600"